### ISSUE TITLE
Hello there when i installed this app its appearing blank..can u pls fix it?

### ISSUE THREAD

**Issue by Aruraka** [godstark82/flixstar#1]

**Comment by godstark82** [comment]
I am sorry but we are currently working on the servers of the app. We'll fix this issue soon. Thanks for waiting.

**Comment by Aruraka** [comment]
> I am sorry but we are currently working on the servers of the app. We'll fix this issue soon. Thanks for waiting.

Okay and can the shows be downloaded in different qualities in this app?

**Comment by godstark82** [comment]
> > I am sorry but we are currently working on the servers of the app. We'll fix this issue soon. Thanks for waiting.
> 
> Okay and can the shows be downloaded in different qualities in this app?

Hey! The Issue has been fixed in the latest update and thanks for addressing the issue for us and yet we have not any plans for downloading movies and series but we'll consider it in future.
